/**
 * Deterministic markdown rendering of the board — the optional, zero-token human
 * mirror (`taskq view`). Pure: rows in, string out. This is an *output*, never a
 * source of truth (the DB is); regenerate it any time for grep/glance/git-diff.
 */

import { TASK_STATUSES, type TaskRow, type TaskStatus } from './types';

/** Status display order (most actionable first). */
const RENDER_ORDER: TaskStatus[] = [
  'ready',
  'claimed',
  'pending_triage',
  'needs_input',
  'blocked',
  'on_hold',
  'not_ready',
  'failed',
  'done',
];

/** Inline `[k:v …]` marker summary for a task (omits empty fields). */
function markers(task: TaskRow, needs: string[]): string {
  const parts: string[] = [];
  if (task.recur_n != null)
    parts.push(task.recur_last != null ? `recur:${task.recur_n} last:${task.recur_last}` : `recur:${task.recur_n}`);
  if (task.slug) parts.push(`id:${task.slug}`);
  if (needs.length) parts.push(`needs:${needs.join(',')}`);
  if (task.group_key) parts.push(`group:${task.group_key}`);
  if (task.repo) parts.push(`repo:${task.repo}`);
  if (task.model) parts.push(`model:${task.model}`);
  if (task.think) parts.push(`think:${task.think}`);
  if (task.fast) parts.push('fast');
  // No-op-OK audit/check tasks: surface the exemption so the board shows why a task
  // can legitimately land no git delta (the false-done gate won't demand one).
  if (task.noop_ok) parts.push('noop-ok');
  // Retry accounting: surface the attempt count (and per-task ceiling, if set) so
  // the zero-token mirror shows "this failed N times" rather than looking pristine.
  if (task.attempts > 0) {
    const ceiling = task.max_attempts != null ? `/${task.max_attempts}` : '';
    parts.push(`attempts:${task.attempts}${ceiling}`);
  }
  return parts.length ? ` [${parts.join(' ')}]` : '';
}

/**
 * Render the board to markdown, grouped by status in {@link RENDER_ORDER}, tasks
 * within a group in priority (`ord`) order. `needsByTask` maps a task id to its
 * `needs:` slugs (omit for none).
 */
export function renderTasksMarkdown(tasks: TaskRow[], needsByTask: Record<number, string[]> = {}): string {
  const byStatus = new Map<TaskStatus, TaskRow[]>();
  for (const s of TASK_STATUSES) byStatus.set(s, []);
  for (const t of [...tasks].sort((a, b) => a.ord - b.ord || a.id - b.id)) byStatus.get(t.status)?.push(t);

  const lines: string[] = [
    '<!-- GENERATED by `taskq view` from taskq.sqlite. Do NOT edit — the DB is the source of truth. -->',
    '',
    '# taskq board',
    '',
  ];
  for (const status of RENDER_ORDER) {
    const group = byStatus.get(status) ?? [];
    if (!group.length) continue;
    lines.push(`## ${status} (${group.length})`, '');
    for (const t of group) {
      const note = t.note ? ` — ${t.note.replace(/\s+/g, ' ').trim()}` : '';
      lines.push(`- #${t.id}${markers(t, needsByTask[t.id] ?? [])} ${t.title}${note}`);
      if (t.body) for (const bl of t.body.split('\n')) lines.push(`  ${bl}`);
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}
